version: "3.6"
services:
  node:
    build: .
    user: "node"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=development
    volumes:
      - codebase-docker-sync:/home/node/app
      - codebase-docker-sync:/home/node/app/book
    ports:
      - "5000:5000"

volumes:
    codebase-docker-sync:
        external: true
    books-docker-sync:
        external: true